"""empty message

Revision ID: 159b29d9f3aa
Revises: f2a6e8b3c9be
Create Date: 2022-03-25 16:26:48.093408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '159b29d9f3aa'
down_revision = 'f2a6e8b3c9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'description')
    op.add_column('review', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'description')
    op.add_column('book', sa.Column('description', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
