"""empty message

Revision ID: 583c18ceb1d6
Revises: 85b2560c8de1
Create Date: 2022-03-30 02:35:41.171221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '583c18ceb1d6'
down_revision = '85b2560c8de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('post_time', sa.DateTime(), nullable=False))
    op.drop_column('review', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('time', mysql.DATETIME(), nullable=False))
    op.drop_column('review', 'post_time')
    # ### end Alembic commands ###
