"""empty message

Revision ID: 731a9a392d9d
Revises: f0b68b90d3c4
Create Date: 2022-04-05 02:18:07.552096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731a9a392d9d'
down_revision = 'f0b68b90d3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('followed_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_user'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower'], ['user.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
