"""empty message

Revision ID: 85b2560c8de1
Revises: d1ff3d96cbff
Create Date: 2022-03-30 01:23:43.420779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b2560c8de1'
down_revision = 'd1ff3d96cbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'time')
    # ### end Alembic commands ###
