"""empty message

Revision ID: 88b492ebcebb
Revises: 731a9a392d9d
Create Date: 2022-04-05 22:45:11.477052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88b492ebcebb'
down_revision = '731a9a392d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed', sa.Integer(), nullable=True))
    op.drop_constraint('followers_ibfk_1', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['followed'], ['id'], ondelete='CASCADE')
    op.drop_column('followers', 'followed_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_user', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_ibfk_1', 'followers', 'user', ['followed_user'], ['id'], ondelete='CASCADE')
    op.drop_column('followers', 'followed')
    # ### end Alembic commands ###
