"""empty message

Revision ID: 9e97be843219
Revises: 583c18ceb1d6
Create Date: 2022-04-01 02:00:02.370989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e97be843219'
down_revision = '583c18ceb1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('text_html', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'text_html')
    # ### end Alembic commands ###
