"""empty message

Revision ID: a6fc742844b7
Revises: e7b67b85dc9d
Create Date: 2022-03-27 23:36:16.061820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fc742844b7'
down_revision = 'e7b67b85dc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_ibfk_2', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_ibfk_2', 'review', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###
