"""empty message

Revision ID: d1ff3d96cbff
Revises: 7207a9fdf444
Create Date: 2022-03-30 00:45:06.380768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ff3d96cbff'
down_revision = '7207a9fdf444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('popularity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'popularity')
    # ### end Alembic commands ###
