"""empty message

Revision ID: e782e3cc8d8f
Revises: 208bef7c8248
Create Date: 2022-03-28 00:27:55.939207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e782e3cc8d8f'
down_revision = '208bef7c8248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'good_marks')
    op.drop_column('review', 'bad_marks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('bad_marks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('review', sa.Column('good_marks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
