"""empty message

Revision ID: edd9aeedd438
Revises: 159b29d9f3aa
Create Date: 2022-03-26 01:15:55.648824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edd9aeedd438'
down_revision = '159b29d9f3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('description', sa.String(length=350), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['id'])
    op.drop_column('review', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('description', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'description')
    op.drop_column('book', 'user_id')
    # ### end Alembic commands ###
